name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      node_version: "18"
      run_tests: true

  docker:
    needs: build-test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: sonali0910/my-app
      tag: sha-${{ github.sha }}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  security-scan:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@v0
        with:
          image-ref: ${{ needs.docker.outputs.image_url }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          output: trivy-report.txt

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

  deploy:
    needs: security-scan
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy
        run: |
          echo "Deploying image: ${{ needs.docker.outputs.image_url }} to production"
